meta_product_name: "Au bord de l'eau"
meta_title: "Au bord de l'eau - Le réseau des pêcheurs et de leurs actions environnementales"
meta_description: "Au bord de l'eau : le nouvel outil des pêcheurs pour vivre lerus passions et s'engager activement pour la préservation de l'environnement."
meta_image: "lancer.jpg"
twitter_account: "@au-bord-deleau"
