meta_product_name: "Au bord de l'eau"
meta_title: "Association au bord de l'eau - Le réseau des pêcheurs et de leurs actions environnementales"
meta_description: "Association Au bord de l'eau est un projet d'association gérant site Internet combinant un réseau social pour rassembler les pêcheurs autour de leur passion et une plate-forme d'actions environnementales pour les inciter à s'engager concrètement."
meta_image: "lancer.jpg"
twitter_account: "@au-bord-deleau"
